In [1]:
import pandas as pd

df = pd.read_csv("./data_cleaned.csv").fillna("")

def merge_rows(group):
    texts = []

    for _, row in group.iterrows():
        if row["heading"]:
            texts.append(f"## {row['heading']}")
        if row["content"]:
            texts.append(row["content"])

    return pd.Series({
        "title": group.iloc[0]["title"],
        "url": group.iloc[0]["url"],
        "text": "\n\n".join(texts)
    })

documents = (
    df.groupby("url", as_index=False)
      .apply(merge_rows)
      .reset_index(drop=True)
)

print(documents.head())

                                               title  \
0   40 tuổi, bị bệnh lupus muốn có con phải làm sao?
1         AMH cao có thể có con tự nhiên được không?
2  AMH là 0,1 có làm IVF bằng trứng của mình được...
3  Bị buồng trứng đa nang, chưa có trứng trội thì...
4  Bị nhiễm sắc thể số 9 thì có mang thai được kh...

                                                 url  \
0  https://tamanhhospital.vn/tu-van/40-tuoi-bi-be...
1  https://tamanhhospital.vn/tu-van/amh-cao-co-co...
2  https://tamanhhospital.vn/tu-van/amh-la-01-co-...
3  https://tamanhhospital.vn/tu-van/bi-buong-trun...
4  https://tamanhhospital.vn/tu-van/bi-nhiem-sac-...

                                                text
0  ## 40 tuổi, bị bệnh lupus muốn có con phải làm...
1  ## AMH cao có thể có con tự nhiên được không?\...
2  ## AMH là 0,1 có làm IVF bằng trứng của mình đ...
3  ## Bị buồng trứng đa nang, chưa có trứng trội ...
4  ## Bị nhiễm sắc thể số 9 thì có mang thai được...

C:\Users\Windows\AppData\Local\Temp\ipykernel_13676\1744706897.py:22: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(merge_rows)

In [ ]:

URI = "bolt://localhost:7687"
USERNAME = "neo4j"
PASSWORD = "123456789"

Import Document

In [ ]:
from neo4j import GraphDatabase
import json

driver = GraphDatabase.driver(
    "bolt://localhost:7687",
    auth=(USERNAME, PASSWORD)
)

def create_document(tx, row):
    query = """
    MERGE (d:Document {url: $url})

    SET d.title = $title,
        d.text = $text,
        d.metadata = $metadata,
        d.text_unit_ids = $text_unit_ids
    """

    tx.run(
        query,
        url=row["url"],
        title=row["title"],
        text=row["text"],
        metadata=json.dumps({"url": row["url"]}),
        text_unit_ids=[]
    )

with driver.session() as session:
    for _, row in documents.iterrows():
        session.execute_write(create_document, row)

driver.close()

Improt Chunk

In [ ]:
from neo4j import GraphDatabase
import pandas as pd

driver = GraphDatabase.driver(
    "bolt://localhost:7687",
    auth=(USERNAME, PASSWORD)
)

df_chunk = pd.read_csv("./content_chunks.csv").fillna("")


def create_chunk(tx, row):
    query = """
    // Bước 1: Tìm Document dựa trên URL có trong file CSV của Chunk
    MATCH (d:Document {url: $url})

    // Bước 2: Tạo hoặc tìm Chunk
    MERGE (c:Chunk {chunk_id: $chunk_id})

    // Bước 3: Gán thuộc tính cho Chunk
    SET
        c.chunk_id = $chunk_id,
        c.chunk_text = $chunk_text,
        c.entity_ids = $entity_ids,
        c.relationships_ids = $relationships_ids,
        c.document_id = elementId(d)

    // Bước 4: Cập nhật text_unit_ids trong node Document
    // Sử dụng biểu thức điều kiện (coalesce) để phòng trường hợp d.text_unit_ids chưa được khởi tạo (null)
    SET d.text_unit_ids = coalesce(d.text_unit_ids, []) + [$chunk_id]

    // Bước 5: Tạo mối quan hệ giữa 2 Node
    MERGE (d)-[:HAS_CHUNK]->(c)
    """

    tx.run(
        query,
        chunk_id=row["chunk_id"],
        chunk_text=row["chunk_text"],
        entity_ids=[],
        relationships_ids=[],
        url=row["url"]
    )

with driver.session() as session:
    for _, row in df_chunk.iterrows():
        session.execute_write(create_chunk, row)

driver.close()

Import Entity

In [6]:
import ast
from neo4j import GraphDatabase
import pandas as pd

driver = GraphDatabase.driver(
    "bolt://localhost:7687",
    auth=(USERNAME, PASSWORD)
)

df = pd.read_csv("./content_chunks_extracted_1-100.csv").fillna("")

def create_entities(tx, row):
    try:
        extracted = ast.literal_eval(row["extracted_text"])
    except Exception as e:
        print(f"Cannot parse chunk {row['chunk_id']}: {e}")
        return

    chunk_id = int(row["chunk_id"])

    for idx, entity in enumerate(extracted.get("entities", [])):
        mention_id = f"{chunk_id}_{idx}"

        tx.run(
            """
            // Bước 1: Tìm Chunk đang xử lý
            MATCH (c:Chunk {chunk_id: $chunk_id})

            // Bước 2: Tạo EntityMention mới
            CREATE (e:EntityMention {
                mention_id: $mention_id,
                chunk_id: $chunk_id,
                name: $name,
                type: $type,
                description: $description,
                chunk_ids: [$chunk_id],
                frequency: 1,
                degree: 0
            })

            // Bước 3: Quay ngược lại cập nhật mảng entity_ids bên trong node Chunk
            // Nếu c.entity_ids chưa được khởi tạo (null), coalesce sẽ tự biến thành mảng rỗng [] để cộng
            SET c.entity_ids = coalesce(c.entity_ids, []) + [$mention_id]

            // Bước 4: Tạo mối quan hệ từ Chunk sang EntityMention
            CREATE (c)-[:MENTIONS]->(e)
            """,
            chunk_id=chunk_id,
            mention_id=mention_id,
            name=entity.get("entity_name", ""),
            type=entity.get("entity_type", ""),
            description=entity.get("entity_description", "")
        )

with driver.session() as session:
    for _, row in df.iterrows():
        session.execute_write(create_entities, row)

driver.close()

Import Relationship

In [7]:
import ast
from neo4j import GraphDatabase
import pandas as pd

driver = GraphDatabase.driver(
    "bolt://localhost:7687",
    auth=(USERNAME, PASSWORD)
)
df = pd.read_csv("./content_chunks_extracted_1-100.csv").fillna("")

def create_relationships(tx, row):
    try:
        extracted = ast.literal_eval(row["extracted_text"])
    except Exception as e:
        print(f"Cannot parse chunk {row['chunk_id']}: {e}")
        return

    chunk_id = int(row["chunk_id"])

    entities = extracted.get("entities", [])
    relationships = extracted.get("relationships", [])

    name_to_mention = {}

    for idx, entity in enumerate(entities):
        mention_id = f"{chunk_id}_{idx}"
        name_to_mention[entity.get("entity_name")] = mention_id

    for rel in relationships:
        source = name_to_mention.get(rel.get("source_entity"))
        target = name_to_mention.get(rel.get("target_entity"))

        if source is None or target is None:
            print(
                f"Skip relationship in chunk {chunk_id}: "
                f"{rel.get('source_entity')} -> {rel.get('target_entity')}"
            )
            continue

        relationship_id = f"{source}_{target}_{idx}" 

        tx.run(
            """
            // Bước 1: Tìm Node Chunk và 2 Node EntityMention liên quan
            MATCH (c:Chunk {chunk_id: $chunk_id})
            MATCH (s:EntityMention {mention_id: $source})
            MATCH (t:EntityMention {mention_id: $target})

            // Bước 2: Tạo mối quan hệ giữa Source và Target
            CREATE (s)-[r:RELATED_TO {
                relationship_id: $relationship_id, // Nên lưu lại ID này trên cạnh để sau này dễ tra cứu
                source: $source,
                target: $target,
                description: $description,
                weight: $weight,
                combined_degree: 0,
                chunk_ids: [$chunk_id]
            }]->(t)

            // Bước 3: Cập nhật danh sách relationships_ids trong node Chunk
            SET c.relationships_ids = coalesce(c.relationships_ids, []) + [$relationship_id]
            """,
            chunk_id=chunk_id,
            relationship_id=relationship_id,
            source=source,
            target=target,
            description=rel.get("relationship_description", ""),
            weight=float(rel.get("relationship_strength", 0))
        )

with driver.session() as session:
    for _, row in df.iterrows():
        session.execute_write(create_relationships, row)

driver.close()

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Entity resolution

In [9]:

URI = "bolt://localhost:7687"
USERNAME = "neo4j"
PASSWORD = "123456789"

In [10]:
from neo4j import GraphDatabase
import pandas as pd

driver = GraphDatabase.driver(
    URI,
    auth=(USERNAME, PASSWORD)
)

query = """
MATCH (e:EntityMention)
RETURN
e.mention_id AS mention_id,
e.name AS name,
e.type AS type
"""

with driver.session() as session:
    result = session.run(query)
    df = pd.DataFrame([r.data() for r in result])

driver.close()

print(df.head())

  mention_id                       name       type
0       12_0                   Pentinox       drug
1       12_1  Bệnh viện Đa khoa Tâm Anh   hospital
2       12_2                   Bệnh tật  condition
3       11_0  Bệnh viện Đa khoa Tâm Anh   hospital
4       11_1  hở khuyết sẹo mổ lấy thai  condition

In [11]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("bkai-foundation-models/vietnamese-bi-encoder")

texts = (
    df["name"].fillna("")
    + "\n"
    + df["type"].fillna("")
).tolist()


embeddings = model.encode(
    texts,
    batch_size=128,
    normalize_embeddings=True,
    show_progress_bar=True
)

Batches: 100%|██████████| 3/3 [00:00<00:00,  3.23it/s]

In [12]:
def write_embedding(tx, mention_id, embedding):
    tx.run(
        """
        MATCH (e:EntityMention {mention_id:$id})
        SET e.embedding=$embedding
        """,
        id=mention_id,
        embedding=embedding.tolist()
    )

In [13]:
BATCH_SIZE = 500

driver = GraphDatabase.driver(
    URI,
    auth=(USERNAME, PASSWORD)
)

with driver.session() as session:

    for start in range(0, len(df), BATCH_SIZE):

        end = min(start + BATCH_SIZE, len(df))

        batch = df.iloc[start:end]

        with session.begin_transaction() as tx:

            for i, row in batch.iterrows():

                write_embedding(
                    tx,
                    row["mention_id"],
                    embeddings[i]
                )

            tx.commit()

        print(end)

driver.close()

356

Group

In [14]:
URI = "bolt://localhost:7687"
USERNAME = "neo4j"
PASSWORD = "123456789"

In [15]:
from graphdatascience import GraphDataScience

gds = GraphDataScience(
    URI,
    auth=(USERNAME, PASSWORD)
)
if gds.graph.exists("entity_mentions")["exists"]:
    gds.graph.drop("entity_mentions")

In [16]:
G, result = gds.graph.project(
    "entity_mentions",
    "EntityMention",
    "*",
    nodeProperties=["embedding"]
)

print(result)

nodeProjection            {'EntityMention': {'properties': {'embedding':...
relationshipProjection    {'__ALL__': {'orientation': 'NATURAL', 'aggreg...
graphName                                                   entity_mentions
nodeCount                                                               356
relationshipCount                                                       291
projectMillis                                                            39
Name: 0, dtype: object

In [17]:
gds.knn.mutate(
    G,
    nodeProperties=["embedding"],
    mutateRelationshipType="SIMILAR",
    mutateProperty="score",
    similarityCutoff=0.80
)

preProcessingMillis                                                       0
computeMillis                                                           147
mutateMillis                                                             98
postProcessingMillis                                                      0
nodesCompared                                                           356
relationshipsWritten                                                   1257
similarityDistribution    {'p1': 0.8003387451171875, 'p5': 0.80900192260...
didConverge                                                            True
ranIterations                                                             7
nodePairsConsidered                                                  132167
configuration             {'topK': 10, 'maxIterations': 100, 'randomJoin...
Name: 0, dtype: object

In [18]:
gds.wcc.write(
    G,
    relationshipTypes=["SIMILAR"],
    writeProperty="wcc"
)

componentCount                                                         144
componentDistribution    {'p1': 1, 'max': 57, 'p5': 1, 'p90': 3, 'p50':...
preProcessingMillis                                                      0
computeMillis                                                            4
postProcessingMillis                                                     1
writeMillis                                                             30
nodePropertiesWritten                                                  356
configuration            {'writeConcurrency': 4, 'seedProperty': None, ...
Name: 0, dtype: object

In [19]:
result = gds.run_cypher("""
MATCH (e:EntityMention)
WITH e.wcc AS community, count(*) AS size
RETURN community, size
ORDER BY size DESC
LIMIT 20
""")

print(result)

    community  size
0          15    57
1           1    36
2           2    22
3          16    19
4          18    15
5          71     9
6           5     7
7         218     6
8         176     5
9          39     5
10         89     5
11        157     4
12         84     4
13        181     3
14        210     3
15         27     3
16        118     3
17         45     3
18         81     3
19         36     3

In [20]:
SYSTEM_PROMPT = """
You are an expert in medical entity resolution.

Your task is to identify entity mentions that refer to the same real-world entity.

Each entity has:
- mention_id
- name
- type
- description

Rules:

1. A mention_id can belong to ONE AND ONLY ONE MergeGroup.

2. Respone members is list mention_id that refer to the same real-world entity.

3. Merge entities with minor spelling differences.

4. Merge abbreviations and full names.

5. Merge different languages referring to the same entity.

6. Use description to understand meaning.

Input entities:

{input_text}
"""

In [21]:
from typing import List
from pydantic import BaseModel, Field


class MergeGroup(BaseModel):
    canonical_name: str = Field(
        description="Canonical entity name."
    )

    canonical_type: str = Field(
        description="Canonical entity type."
    )

    canonical_description: str = Field(
        description="Merged description of the entity."
    )

    members: List[str] = Field(
        description="List of mention_id"
    )


class EntityResolutionResult(BaseModel):
    groups: List[MergeGroup]

In [22]:
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(
    api_key="lm-studio",
    base_url="http://localhost:8000/v1",
    model="qwen-3-1.7b",
    temperature=0,
    extra_body={
        "chat_template_kwargs": {
            "enable_thinking": False
        }
    },
)

structured_llm = llm.with_structured_output(EntityResolutionResult)

In [23]:
def build_prompt(text: str) -> str:
    return SYSTEM_PROMPT.format(
        input_text=text
    )

In [24]:
def resolve_one_community(community_id, entities):

    try:
        prompt = build_prompt(entities)
        response = structured_llm.invoke([
            {
                "role": "system",
                "content": "You are an expert in information extraction."
            },
            {
                "role": "user",
                "content": prompt
            }
        ])
        return {
            "community": community_id,
            "groups": response.groups
        }

    except Exception as e:

        print(f"Community {community_id} failed:", e)

        return None

In [25]:
communities = gds.run_cypher("""

MATCH (e:EntityMention)

WITH e.wcc AS community,

collect({

    mention_id:e.mention_id,

    name:e.name,

    type:e.type,

    description:e.description

}) AS entities

WHERE size(entities) > 1

RETURN community, entities

""")

In [26]:
from pprint import pprint

for _, row in communities.iterrows():
    print("=" * 80)
    print("Community:", row.community)
    pprint(row.entities)

================================================================================
Community: 1
[{'description': "A hospital where the patient's question was referred for "
                 'further assessment.',
  'mention_id': '12_1',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': "A hospital providing medical care for women's health issues, "
                 'particularly related to pregnancy and childbirth.',
  'mention_id': '11_0',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A hospital that provides medical care, specifically '
                 "addressing the patient's concerns about radiation exposure "
                 'during pregnancy.',
  'mention_id': '2_0',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A hospital that provides medical care and services, '
                 'including prenatal care and consultation for pregnant women.',
  'mention_id': '0_0',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': "A hospital providing medical care, where the patient's "
                 'question was referred for consultation.',
  'mention_id': '5_0',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A hospital providing medical care, specifically for '
                 'obstetrics and gynecology, and offering surgical '
                 'interventions for conditions like labial frenulum resection.',
  'mention_id': '13_0',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A hospital providing prenatal care for high-risk '
                 'pregnancies.',
  'mention_id': '14_0',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': "A hospital where the patient's question was referred, and "
                 "the doctor is authorized to answer the patient's concerns.",
  'mention_id': '9_0',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A healthcare facility that provides medical services, '
                 'including diagnostic tests and treatments.',
  'mention_id': '6_9',
  'name': 'Hospital',
  'type': 'hospital'},
 {'description': 'A hospital providing medical care, where the patient is '
                 'referred for further evaluation and management.',
  'mention_id': '3_0',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A hospital providing medical care, specifically addressing '
                 'maternal and fetal health issues.',
  'mention_id': '1_0',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A modern hospital offering comprehensive medical services, '
                 'including effective treatment plans according to '
                 'international standards, and supporting patients with '
                 'assistance. It is dedicated to helping patients schedule '
                 'early appointments for consultations.',
  'mention_id': '23_0',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'organization'},
 {'description': 'A hospital providing medical consultation and diagnostic '
                 'services.',
  'mention_id': '26_1',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A multi-specialty hospital that provides comprehensive '
                 'reproductive care, including diagnostic tests, treatment '
                 'plans, and patient support services.',
  'mention_id': '25_4',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A hospital providing comprehensive medical care, including '
                 'prenatal services and maternal health monitoring.',
  'mention_id': '31_3',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A telephone number for patients to contact for medical '
                 'assistance and support.',
  'mention_id': '31_4',
  'name': 'Tổng đài Bệnh viện Đa khoa Tâm Anh',
  'type': 'concept'},
 {'description': 'A hospital that provides comprehensive medical care, '
                 'including gynecological and reproductive health services, '
                 'with experienced doctors and modern equipment.',
  'mention_id': '27_2',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A hospital providing comprehensive medical care, including '
                 'vaccination services, in Hanoi and Ho Chi Minh City.',
  'mention_id': '30_4',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A hospital that gathers a team of experienced doctors, '
                 'modern equipment, and offers a variety of comprehensive '
                 'medical check-ups and health care packages for women, ready '
                 'to support patients.',
  'mention_id': '32_1',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A healthcare system providing medical support, including '
                 'consultations and assistance for couples seeking '
                 'reproductive health services.',
  'mention_id': '35_2',
  'name': 'Hệ thống bệnh viện Đa khoa Tâm Anh',
  'type': 'organization'},
 {'description': 'A hospital specializing in gynecological care, offering '
                 'comprehensive medical services for women, including '
                 'diagnostic and treatment options for conditions like '
                 'recurrent miscarriage.',
  'mention_id': '33_2',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A healthcare system providing medical services, including '
                 'IVF and egg donation support, located in Hà Nội and TP.HCM.',
  'mention_id': '36_8',
  'name': 'Hệ thống bệnh viện Đa khoa Tâm Anh',
  'type': 'organization'},
 {'description': 'A hospital in Hanoi providing medical services, including '
                 'maternal care and vaccination.',
  'mention_id': '28_8',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A hospital where patients are treated and where specialists '
                 'perform medical examinations and treatments.',
  'mention_id': '44_0',
  'name': 'Bệnh viện',
  'type': 'hospital'},
 {'description': 'A hospital providing services for childbirth, with contact '
                 'information for cost consultation.',
  'mention_id': '41_0',
  'name': 'Tâm Anh',
  'type': 'hospital'},
 {'description': 'A hospital offering services for childbirth, with contact '
                 'information for cost consultation.',
  'mention_id': '41_1',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A hotline for the hospital, providing cost consultation '
                 'services.',
  'mention_id': '41_6',
  'name': 'Tổng đài Bệnh viện Đa khoa Tâm Anh',
  'type': 'concept'},
 {'description': 'A hospital where the patient can receive medical '
                 'consultation and treatment for the condition described.',
  'mention_id': '7_1',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A hospital that provides comprehensive gynecological care, '
                 'including examinations and health services for women, and is '
                 'equipped with modern facilities and experienced medical '
                 'staff.',
  'mention_id': '34_0',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A phone number for the Heart of Hope Hospital, providing '
                 'support for patients to book appointments with specialists.',
  'mention_id': '43_7',
  'name': 'Tổng đài Bệnh viện Đa khoa Tâm Anh',
  'type': 'concept'},
 {'description': 'A hospital that performs PGS (preimplantation genetic '
                 'screening) to exclude genetic disorders in all chromosomes.',
  'mention_id': '46_1',
  'name': 'IVF Tâm Anh',
  'type': 'hospital'},
 {'description': "A hospital providing medical care, where the patient's "
                 'condition is being evaluated and discussed with the doctor.',
  'mention_id': '8_0',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A hospital providing medical support, with contact numbers '
                 'for inquiries.',
  'mention_id': '29_3',
  'name': 'Bệnh viện Đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A hospital providing medical care, with a focus on '
                 'reproductive health and support for pregnant women.',
  'mention_id': '24_0',
  'name': 'BVĐK Tâm Anh',
  'type': 'hospital'},
 {'description': 'A hospital providing reproductive assistance through sperm '
                 'donation, following legal guidelines for anonymous donation '
                 'between donors and recipients.',
  'mention_id': '16_0',
  'name': 'Bệnh viện đa khoa Tâm Anh',
  'type': 'hospital'},
 {'description': 'A medical facility that provides healthcare services, '
                 'including diagnostic and treatment services for various '
                 'conditions.',
  'mention_id': '38_9',
  'name': 'hospital',
  'type': 'hospital'}]
================================================================================
Community: 2
[{'description': 'A general term for a disease or illness, which is mentioned '
                 "in the context of the drug's contraindications.",
  'mention_id': '12_2',
  'name': 'Bệnh tật',
  'type': 'condition'},
 {'description': 'The period of pregnancy, particularly the first trimester, '
                 'where radiation exposure may have significant effects.',
  'mention_id': '2_2',
  'name': 'Thai kỳ',
  'type': 'condition'},
 {'description': 'A high risk for complications during pregnancy, requiring '
                 'close monitoring and specialized care.',
  'mention_id': '14_7',
  'name': 'Nguy cơ cao',
  'type': 'risk_factor'},
 {'description': 'A condition referring to a healthy baby born, but the '
                 'patient had two previous miscarriages in the 8th and 9th '
                 'weeks.',
  'mention_id': '9_1',
  'name': 'Bệnh thai',
  'type': 'condition'},
 {'description': 'A condition where the baby is lost during pregnancy, '
                 'commonly occurring in the 8th and 9th weeks.',
  'mention_id': '9_2',
  'name': 'Thai lưu',
  'type': 'condition'},
 {'description': 'A condition where a pregnancy ends before 20 weeks, often '
                 'due to various factors.',
  'mention_id': '9_6',
  'name': 'Sảy thai',
  'type': 'condition'},
 {'description': 'A complication where the pregnancy ends prematurely, often '
                 'before 20 weeks, with increased risk in women with this '
                 'condition.',
  'mention_id': '3_3',
  'name': 'Sẩy thai',
  'type': 'symptom'},
 {'description': 'A condition where the pregnancy ends before 20 weeks, often '
                 'due to complications from infections.',
  'mention_id': '1_7',
  'name': 'Sảy thai',
  'type': 'condition'},
 {'description': 'A condition where the pregnancy ends before 20 weeks, often '
                 'due to complications from infections.',
  'mention_id': '1_8',
  'name': 'Thai chết lưu',
  'type': 'condition'},
 {'description': 'A birth defect that can result from infections during '
                 'pregnancy.',
  'mention_id': '1_9',
  'name': 'Dị tật bẩm sinh',
  'type': 'condition'},
 {'description': 'A common respiratory infection characterized by symptoms '
                 'such as fever, cough, and sore throat.',
  'mention_id': '26_2',
  'name': 'Cảm cúm',
  'type': 'condition'},
 {'description': 'A contagious disease caused by the SARS-CoV-2 virus. It can '
                 'lead to severe respiratory issues, hospitalization, and '
                 'death in some cases.',
  'mention_id': '31_1',
  'name': 'Covid-19',
  'type': 'condition'},
 {'description': 'A contagious disease caused by the SARS-CoV-2 virus, leading '
                 'to a range of symptoms from mild to severe, including '
                 'respiratory issues and complications.',
  'mention_id': '30_1',
  'name': 'Covid-19',
  'type': 'condition'},
 {'description': 'A condition that increases the risk of birth defects, '
                 'potentially linked to certain medications or exposures.',
  'mention_id': '30_8',
  'name': 'Dị tật thai nhi',
  'type': 'risk_factor'},
 {'description': 'A recurrent miscarriage, a condition where a pregnancy ends '
                 'before 20 weeks of gestation, often without knowing the '
                 'cause. It is a common reproductive health issue that can be '
                 'challenging to manage.',
  'mention_id': '33_0',
  'name': 'sảy thai',
  'type': 'condition'},
 {'description': 'A risk factor for recurrent miscarriage, indicating a higher '
                 'likelihood of experiencing another miscarriage after a '
                 'previous one.',
  'mention_id': '33_1',
  'name': 'nguy cơ sảy thai',
  'type': 'risk_factor'},
 {'description': 'A recurrence of miscarriage, indicating a potential need for '
                 'further medical evaluation and treatment to prevent future '
                 'miscarriages.',
  'mention_id': '33_7',
  'name': 'sảy thai lần nữa',
  'type': 'condition'},
 {'description': 'A contagious respiratory illness caused by the SARS-CoV-2 '
                 'virus, which can lead to severe complications and death.',
  'mention_id': '28_0',
  'name': 'Covid-19',
  'type': 'disease'},
 {'description': 'A condition where the fetus dies in the womb and is not '
                 'delivered, often associated with increased health risks.',
  'mention_id': '28_5',
  'name': 'Thai chết lưu',
  'type': 'condition'},
 {'description': 'A twin pregnancy is a high-risk pregnancy with increased '
                 'rates of miscarriage and preterm birth compared to a '
                 'singleton pregnancy.',
  'mention_id': '45_0',
  'name': 'Thai đôi',
  'type': 'condition'},
 {'description': 'Miscarriage is a symptom of high-risk pregnancy, '
                 'particularly in twin pregnancies.',
  'mention_id': '45_1',
  'name': 'sảy thai',
  'type': 'symptom'},
 {'description': 'A miscarriage, a medical condition characterized by the loss '
                 'of a pregnancy before the 20th week of gestation.',
  'mention_id': '10_2',
  'name': 'sảy thai',
  'type': 'condition'}]
================================================================================
Community: 5
[{'description': 'A gynecological ultrasound performed using a vaginal '
                 'speculum to check for abnormalities in the reproductive '
                 'system.',
  'mention_id': '11_2',
  'name': 'siêu âm phụ khoa qua đầu dò âm đạo',
  'type': 'test'},
 {'description': 'An ultrasound examination performed to check the condition '
                 'of the uterus.',
  'mention_id': '5_2',
  'name': 'Siêu âm',
  'type': 'test'},
 {'description': 'An ultrasound to examine the reproductive system and assess '
                 'fertility.',
  'mention_id': '19_9',
  'name': 'Siêu âm',
  'type': 'procedure'},
 {'description': 'A diagnostic imaging technique used to visualize internal '
                 "structures, which may be performed to assess the patient's "
                 'condition.',
  'mention_id': '8_2',
  'name': 'Siêu âm',
  'type': 'test'},
 {'description': 'An ultrasound examination, which was performed to assess the '
                 "condition of the patient's ovary and is currently showing "
                 'normal results.',
  'mention_id': '40_2',
  'name': 'Siêu âm',
  'type': 'test'},
 {'description': 'An ultrasound, a medical imaging technique used to visualize '
                 'internal organs and detect abnormalities.',
  'mention_id': '10_4',
  'name': 'siêu âm',
  'type': 'procedure'},
 {'description': 'An ultrasound to count the secondary follicles in the ovary.',
  'mention_id': '42_14',
  'name': 'Siêu âm đếm nang thứ cấp',
  'type': 'procedure'}]
================================================================================
Community: 13
[{'description': 'A drug used to treat parasitic infections, with specific '
                 'contraindications for pregnant women.',
  'mention_id': '0_1',
  'name': 'Thuốc tẩy giun',
  'type': 'drug'},
 {'description': 'A drug used to prevent blood clots, ensuring safety during '
                 'pregnancy.',
  'mention_id': '5_5',
  'name': 'Thuốc chống đông',
  'type': 'drug'}]
================================================================================
Community: 15
[{'description': 'A department within the hospital specializing in prenatal '
                 'care and gynecological services.',
  'mention_id': '0_3',
  'name': 'Trung tâm Sản Phụ khoa',
  'type': 'location'},
 {'description': 'A center for obstetrics and gynecology, where patients can '
                 'receive detailed consultation and advice on surgical '
                 'interventions.',
  'mention_id': '13_6',
  'name': 'Trung tâm Sản Phụ khoa',
  'type': 'organization'},
 {'description': 'A greeting message indicating the start of a consultation '
                 'for reproductive health issues.',
  'mention_id': '15_0',
  'name': 'Chào bạn!',
  'type': 'concept'},
 {'description': 'The process of scheduling a check-up and consultation, which '
                 'is part of the reproductive health assessment.',
  'mention_id': '15_7',
  'name': 'đặt lịch khám và tư vấn',
  'type': 'concept'},
 {'description': 'A reproductive health support center offering consultations '
                 'and check-ups.',
  'mention_id': '15_9',
  'name': 'IVFTA',
  'type': 'concept'},
 {'description': 'In vitro fertilization, a reproductive technology used to '
                 'assist couples with infertility, requiring a gynecological '
                 'examination before the procedure.',
  'mention_id': '18_1',
  'name': 'IVF',
  'type': 'procedure'},
 {'description': 'A reproductive assistance center providing IVF services, '
                 'offering support for infertility treatments.',
  'mention_id': '18_3',
  'name': 'IVFTA',
  'type': 'organization'},
 {'description': 'A reproductive healthcare center offering IVF (in vitro '
                 'fertilization) treatment, providing diagnostic and '
                 'therapeutic services for infertility.',
  'mention_id': '17_3',
  'name': 'Trung tâm Hỗ trợ sinh sản IVFTA',
  'type': 'organization'},
 {'description': 'A general term for a mass or collection of cells, which can '
                 'be benign or malignant, and is often associated with '
                 'conditions like endometrial cancer or polyps.',
  'mention_id': '6_1',
  'name': 'U',
  'type': 'concept'},
 {'description': 'A department within the hospital specializing in obstetrics '
                 'and gynecology, where the patient is referred for further '
                 'evaluation.',
  'mention_id': '3_5',
  'name': 'Trung tâm Sản Phụ khoa',
  'type': 'location'},
 {'description': 'Provided by the hospital to assist patients in making '
                 'informed decisions about their healthcare.',
  'mention_id': '23_1',
  'name': 'Tư vấn',
  'type': 'concept'},
 {'description': 'Experts at the hospital who provide specialized care and '
                 'guidance to patients.',
  'mention_id': '23_2',
  'name': 'Chuyên gia',
  'type': 'concept'},
 {'description': 'The process of scheduling an appointment with a specialist '
                 'at the hospital.',
  'mention_id': '23_3',
  'name': 'Đặt lịch khám',
  'type': 'concept'},
 {'description': 'IVFTA stands for In Vitro Fertilization and Embryo Transfer, '
                 'a procedure used to assist in reproductive health.',
  'mention_id': '21_5',
  'name': 'IVFTA',
  'type': 'concept'},
 {'description': 'A reproductive health support center providing services '
                 'related to fertility and assisted reproduction.',
  'mention_id': '21_6',

In [27]:
from concurrent.futures import ThreadPoolExecutor, as_completed

MAX_WORKERS = 16

results = []

with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:

    futures = {

        executor.submit(
            resolve_one_community,
            row.community,
            row.entities
        ): row.community

        for _, row in communities.iterrows()

    }

    total = len(futures)

    for idx, future in enumerate(as_completed(futures), 1):

        result = future.result()

        if result:
            results.append(result)

        print(f"{idx}/{total}")


# results = []
# for _, row in communities.iterrows():
#     print(f"Processing community {row.community}...")
#     result = resolve_one_community(row.community, row.entities)
#     if result:
#         results.append(result)

1/36
2/36
3/36
4/36
5/36
6/36
7/36
8/36
9/36
10/36
11/36
12/36
13/36
14/36
15/36
16/36
17/36
18/36
19/36
20/36
21/36
22/36
23/36
24/36
25/36
26/36
27/36
28/36
29/36
30/36
31/36
32/36
33/36
34/36
35/36
Community 15 failed: Could not parse response content as the length limit was reached - CompletionUsage(completion_tokens=1050, prompt_tokens=3046, total_tokens=4096, completion_tokens_details=None, prompt_tokens_details=None)
36/36

In [28]:
merge_data = []
used_mentions = set()

for community in results:
    for group in community["groups"]:

        # Chỉ giữ những mention chưa từng được dùng
        members = [
            m for m in group.members
            if m not in used_mentions
        ]

        # MergeGroup phải có ít nhất 2 entity
        if len(members) < 2:
            continue

        merge_data.append({
            "target": members[0],
            "members": members,
            "canonical_name": group.canonical_name,
            "canonical_type": group.canonical_type,
            "canonical_description": group.canonical_description,
        })

        # Đánh dấu đã sử dụng
        used_mentions.update(members)

In [29]:
all_members = []

for g in merge_data:
    all_members.extend(g["members"])

from collections import Counter

dup = {
    k: v
    for k, v in Counter(all_members).items()
    if v > 1
}

print(dup)

{}

In [30]:
from pprint import pprint

pprint(merge_data)

[{'canonical_description': 'The unborn child, from the time of conception '
                           'until birth. It is the subject of prenatal care '
                           'and monitoring.',
  'canonical_name': 'Thai nhi',
  'canonical_type': 'body_part',
  'members': ['1_6', '31_2', '30_2', '28_1', '29_1'],
  'target': '1_6'},
 {'canonical_description': 'A female individual, likely the patient, who is '
                           'undergoing hormonal testing and is experiencing '
                           'polycystic ovary syndrome (PCOS) and is seeking '
                           'reproductive healthcare.',
  'canonical_name': 'Chị',
  'canonical_type': 'person',
  'members': ['5_1', '17_0', '20_0', '26_0', '22_6', '19_0', '40_0', '10_0'],
  'target': '5_1'},
 {'canonical_description': 'The spouse of the patient, involved in the '
                           'reproductive health assessment and evaluation.',
  'canonical_name': 'Vợ',
  'canonical_type': 'person',
  'members': ['19_1', '19_2'],
  'target': '19_1'},
 {'canonical_description': 'A hospital providing comprehensive medical care, '
                           'including prenatal care, reproductive health '
                           'services, and gynecological care, with modern '
                           'facilities and experienced medical staff.',
  'canonical_name': 'Bệnh viện Đa khoa Tâm Anh',
  'canonical_type': 'hospital',
  'members': ['12_1',
              '11_0',
              '2_0',
              '0_0',
              '5_0',
              '13_0',
              '14_0',
              '9_0',
              '6_9',
              '3_0',
              '1_0',
              '23_0',
              '26_1',
              '25_4',
              '31_3',
              '31_4',
              '27_2',
              '30_4',
              '32_1',
              '35_2',
              '33_2',
              '36_8',
              '28_8',
              '44_0',
              '41_0',
              '41_1',
              '41_6',
              '7_1',
              '34_0',
              '43_7',
              '46_1',
              '8_0',
              '29_3',
              '24_0',
              '16_0'],
  'target': '12_1'},
 {'canonical_description': 'The uterus is a female reproductive organ that can '
                           'be affected by this condition, leading to '
                           'potential complications during pregnancy.',
  'canonical_name': 'Uterus',
  'canonical_type': 'body_part',
  'members': ['6_5', '3_2', '20_2', '39_3'],
  'target': '6_5'},
 {'canonical_description': 'A pregnant woman who may be infected with '
                           'Toxoplasma or CMV, posing a risk to the fetus.',
  'canonical_name': 'Thai phụ',
  'canonical_type': 'person',
  'members': ['14_5', '1_5'],
  'target': '14_5'},
 {'canonical_description': 'The process of giving birth, which requires '
                           'elasticity and elasticity of the labial frenulum '
                           'to prevent tearing.',
  'canonical_name': 'Sinh sản',
  'canonical_type': 'procedure',
  'members': ['13_3', '41_3', '41_4'],
  'target': '13_3'},
 {'canonical_description': 'A phone number provided by the hospital for '
                           'patients to contact for assistance in scheduling '
                           'appointments.',
  'canonical_name': 'Tổng đài',
  'canonical_type': 'concept',
  'members': ['23_5', '25_8'],
  'target': '23_5'},
 {'canonical_description': 'A gynecological examination to assess reproductive '
                           'health and fertility.',
  'canonical_name': 'Khám phụ khoa',
  'canonical_type': 'procedure',
  'members': ['19_8', '10_3', '42_1', '42_3'],
  'target': '19_8'},
 {'canonical_description': 'A condition where the baby is born before 37 weeks '
                           'of gestation, often associated with increased '
                           'health risks.',
  'canonical_name': 'sinh non',
  'canonical_type': 'condition',
  'members': ['28_4', '45_2'],
  'target': '28_4'},
 {'canonical_description': 'A parasitic infection caused by Toxoplasma gondii, '
                           'which can be transmitted to the fetus if '
                           'contracted during pregnancy.',
  'canonical_name': 'Toxoplasma gondii',
  'canonical_type': 'disease',
  'members': ['1_1', '1_3'],
  'target': '1_1'},
 {'canonical_description': 'A viral infection caused by cytomegalovirus, which '
                           'can lead to severe complications in the fetus if '
                           'contracted during pregnancy.',
  'canonical_name': 'Cytomegalovirus (CMV)',
  'canonical_type': 'disease',
  'members': ['1_2', '1_4'],
  'target': '1_2'},
 {'canonical_description': 'The use of contraceptive methods is prohibited, '
                           'emphasizing the importance of natural fertility.',
  'canonical_name': 'không sử dụng biện pháp tránh thai',
  'canonical_type': 'concept',
  'members': ['35_4', '35_5'],
  'target': '35_4'},
 {'canonical_description': 'A test to assess reproductive hormones and '
                           'fertility status.',
  'canonical_name': 'Xét nghiệm nội tiết sinh sản',
  'canonical_type': 'test',
  'members': ['19_3', '42_13'],
  'target': '19_3'},
 {'canonical_description': 'A miscarriage, a medical condition characterized '
                           'by the loss of a pregnancy before the 20th week of '
                           'gestation.',
  'canonical_name': 'sảy thai',
  'canonical_type': 'condition',
  'members': ['12_2',
              '2_2',
              '3_3',
              '31_1',
              '30_1',
              '30_8',
              '33_0',
              '33_1',
              '33_7',
              '10_2'],
  'target': '12_2'},
 {'canonical_description': 'A birth defect that can result from infections '
                           'during pregnancy.',
  'canonical_name': 'Dị tật bẩm sinh',
  'canonical_type': 'condition',
  'members': ['9_1', '9_2', '9_6'],
  'target': '9_1'},
 {'canonical_description': 'The menstrual cycle of women in reproductive age '
                           '(21–35 years old) is considered normal, from the '
                           'first day of one cycle to the first day of the '
                           'next. However, the length of the cycle may be '
                           'affected by neurological factors and health '
                           'status. If your cycle is within the normal range, '
                           'there is no need to be concerned. If you are still '
                           'worried about your condition, you should visit the '
                           'Obstetrics and Gynecology Center at Tâm Anh '
                           'Hospital.',
  'canonical_name': 'Chu kỳ kinh',
  'canonical_type': 'condition',
  'members': ['32_0', '32_4', '32_5'],
  'target': '32_0'},
 {'canonical_description': 'A procedure used to diagnose or monitor a '
                           'condition, such as a blood test or ultrasound, to '
                           'assess the health of the reproductive system.',
  'canonical_name': 'test',
  'canonical_type': 'test',
  'members': ['10_5', '34_3', '38_7'],
  'target': '10_5'},
 {'canonical_description': 'A medical procedure involving the administration '
                           'of a vaccine to the body, typically through '
                           'injection.',
  'canonical_name': 'Tiêm vaccine',
  'canonical_type': 'procedure',
  'members': ['30_5', '30_9', '28_9'],
  'target': '30_5'},
 {'canonical_description': 'A medical professional who provides diagnosis and '
                           'treatment, with experience and modern facilities '
                           'at the hospital.',
  'canonical_name': 'Bác sĩ',
  'canonical_type': 'doctor',
  'members': ['0_4',
              '14_6',
              '6_8',
              '20_5',
              '22_5',
              '25_5',
              '27_5',
              '30_3',
              '32_3',
              '33_4',
              '44_2',
              '7_2',
              '34_2',
              '43_1',
              '45_4',
              '8_4',
              '10_1',
              '24_1',
              '38_8'],
  'target': '0_4'},
 {'canonical_description': 'An ultrasound examination performed to check the '
                           "condition of the patient's ovary and is currently "
                           'showing normal results.',
  'canonical_name': 'Siêu âm',
  'canonical_type': 'test',
  'members': ['5_2', '8_2', '10_4', '40_2', '42_14'],
  'target': '5_2'},
 {'canonical_description': 'A vaccine is a biological product used to prevent '
                           'disease by stimulating the immune system to '
                           'recognize and fight pathogens.',
  'canonical_name': 'Vaccine',
  'canonical_type': 'drug',
  'members': ['30_0', '28_3'],
  'target': '30_0'},
 {'canonical_description': 'A phone number for the hospital in Hanoi.',
  'canonical_name': '024 3872 3872',
  'canonical_type': 'number',
  'members': ['36_9', '41_7', '29_4'],
  'target': '36_9'},
 {'canonical_description': 'A phone number for the hospital in Ho Chi Minh '
                           'City.',
  'canonical_name': '0287 102 6789',
  'canonical_type': 'number',
  'members': ['36_10', '41_8', '29_5'],
  'target': '36_10'}]

In [31]:
cypher="""UNWIND $groups AS group

MATCH (e:EntityMention)
WHERE e.mention_id IN group.members

WITH group, collect(e) AS nodes

CALL apoc.refactor.mergeNodes(
    nodes,
    {
        properties:{
            `.*`:'discard'
        }
    }
)
YIELD node

SET
    node.name = group.canonical_name,
    node.type = group.canonical_type,
    node.description = group.canonical_description

RETURN count(node)"""

In [32]:
gds.run_cypher(
    cypher,
    params={"groups": merge_data}
)

   count(node)
0           24

In [33]:
cypher="""MATCH (a:EntityMention)-[r]->(b:EntityMention)

WITH
    a,
    b,
    type(r) AS rel_type,
    r.relation AS relation,
    collect(r) AS rels,
    sum(r.strength) AS total_strength

WHERE size(rels) > 1

CALL apoc.refactor.mergeRelationships(
    rels,
    {
        properties:"discard"
    }
)
YIELD rel

SET rel.strength = total_strength

RETURN count(*)
"""

In [34]:
gds.run_cypher(
    cypher,
    params={"groups": merge_data}
)

   count(*)
0        20

In [35]:
gds.close()

Constructing and summarizing communities

In [1]:
URI = "bolt://localhost:7687"
USERNAME = "neo4j"
PASSWORD = "123456789"

In [2]:
from graphdatascience import GraphDataScience

gds = GraphDataScience(
    URI,
    auth=(USERNAME, PASSWORD)
)

d:\HocTap\ChatBot\Medical_Chatbot\Data_LakeHouse\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
if gds.graph.exists("communities")["exists"]:
    gds.graph.drop("communities")

G, result = gds.graph.project(
    "communities",
    "EntityMention",
    {
        "_ALL_": {
            "type": "*",
            "orientation": "UNDIRECTED",
            "properties": "weight",
        }
    },
)

print(result)

nodeProjection            {'EntityMention': {'properties': {}, 'label': ...
relationshipProjection    {'_ALL_': {'orientation': 'UNDIRECTED', 'aggre...
graphName                                                       communities
nodeCount                                                               251
relationshipCount                                                       522
projectMillis                                                            25
Name: 0, dtype: object

In [4]:
wcc = gds.wcc.stats(G)

print(f"Component count: {wcc['componentCount']}")
print(f"Component distribution: {wcc['componentDistribution']}")

Component count: 33
Component distribution: {'p1': 1, 'max': 176, 'p5': 1, 'p90': 6, 'p50': 1, 'p95': 7, 'p10': 1, 'p75': 3, 'p99': 176, 'p25': 1, 'min': 1, 'mean': 7.606060606060606, 'p999': 176}

In [5]:
leiden_result = gds.leiden.write(
    G,
    writeProperty="communities",
    includeIntermediateCommunities=True,
    relationshipWeightProperty="weight"
)

print(leiden_result)

ranLevels                                                                3
didConverge                                                           True
nodeCount                                                              251
communityCount                                                          44
preProcessingMillis                                                      0
computeMillis                                                          163
postProcessingMillis                                                    14
writeMillis                                                             27
nodePropertiesWritten                                                  251
communityDistribution    {'p1': 1, 'max': 55, 'p5': 1, 'p90': 12, 'p50'...
modularities             [0.6694275662745627, 0.7173008520088625, 0.719...
modularity                                                        0.719674
configuration            {'writeConcurrency': 4, 'consecutiveIds': Fals...
Name: 0, dtype: object

In [6]:
cypher = """
MATCH (e:EntityMention)

UNWIND range(0, size(e.communities)-1) AS level

MERGE (c:Community {
    id: toString(level) + "-" + toString(e.communities[level])
})
ON CREATE SET
    c.level = level,
    c.community_id = e.communities[level]

MERGE (e)-[:IN_COMMUNITY]->(c)
"""

gds.run_cypher(cypher)

Empty DataFrame
Columns: []
Index: []

In [7]:
cypher = """
MATCH (e:EntityMention)

UNWIND range(1, size(e.communities)-1) AS level

MERGE (parent:Community {
    id: toString(level-1) + "-" + toString(e.communities[level-1])
})

MERGE (child:Community {
    id: toString(level) + "-" + toString(e.communities[level])
})

MERGE (parent)-[:IN_COMMUNITY]->(child)
"""

gds.run_cypher(cypher)

Empty DataFrame
Columns: []
Index: []

In [8]:
cypher = """
MATCH (c:Community)
<-[:IN_COMMUNITY]-
(:EntityMention)
<-[:MENTIONS]-
(:Chunk)
<-[:HAS_CHUNK]-
(d:Document)

WITH c, count(DISTINCT d) AS rank

SET c.community_rank = rank
"""

gds.run_cypher(cypher)

Empty DataFrame
Columns: []
Index: []

In [9]:
import pandas as pd
import numpy as np


community_size = gds.run_cypher(
    """
MATCH (c:Community)<-[:IN_COMMUNITY*]-(e:EntityMention)
WITH c, count(distinct e) AS entities
RETURN split(c.id, '-')[0] AS level, entities
"""
)
community_size_df = pd.DataFrame.from_records(community_size)
percentiles_data = []
for level in community_size_df["level"].unique():
    subset = community_size_df[community_size_df["level"] == level]["entities"]
    num_communities = len(subset)
    percentiles = np.percentile(subset, [25, 50, 75, 90, 99])
    percentiles_data.append(
        [
            level,
            num_communities,
            percentiles[0],
            percentiles[1],
            percentiles[2],
            percentiles[3],
            percentiles[4],
            max(subset)
        ]
    )

# Create a DataFrame with the percentiles
percentiles_df = pd.DataFrame(
    percentiles_data,
    columns=[
        "Level",
        "Number of communities",
        "25th Percentile",
        "50th Percentile",
        "75th Percentile",
        "90th Percentile",
        "99th Percentile",
        "Max"
    ],
)
percentiles_df

C:\Users\Windows\AppData\Local\Temp\ipykernel_27580\1477743568.py:12: FutureWarning: Passing a DataFrame to DataFrame.from_records is deprecated. Use set_index and/or drop to modify the DataFrame instead.
  community_size_df = pd.DataFrame.from_records(community_size)

,Level,Number of communities,25th Percentile,50th Percentile,75th Percentile,90th Percentile,99th Percentile,Max
0,2,44,1.0,3.0,5.25,15.5,51.56,55
1,0,63,1.0,3.0,4.00,6.8,26.16,46
2,1,44,1.0,3.0,5.25,15.5,41.67,55

Comunity Report

In [10]:
cypher = """
MATCH (c:Community)<-[:IN_COMMUNITY]-(e:EntityMention)
WHERE c.level IN [0,1,2]

WITH c, collect(e) AS nodes
WHERE size(nodes) > 1

CALL apoc.path.subgraphAll(
    nodes[0],
    {
        whitelistNodes: nodes
    }
)
YIELD relationships

RETURN
    c.id AS communityId,
    c.level AS level,

    [n IN nodes |
        {
            id: elementId(n),
            name: n.name,
            description: n.description
        }
    ] AS nodes,

    [r IN relationships |
        {
            start: startNode(r).name,
            type: type(r),
            end: endNode(r).name,
            description: r.description,
            weight: r.weight
        }
    ] AS rels

ORDER BY level, communityId
"""

community_info = gds.run_cypher(cypher)

community_info = community_info.to_dict("records")

print(len(community_info))
for community in community_info[:5]:
    print("=" * 80)
    print(f"Community ID: {community['communityId']}, Level: {community['level']}")
    print("Nodes:")
    for node in community["nodes"]:
        print(f"  - ID: {node['id']}, Name: {node['name']}, Description: {node['description']}")
    print("Relationships:")
    for rel in community["rels"]:
        print(f"  - Start: {rel['start']}, Type: {rel['type']}, End: {rel['end']}, Description: {rel['description']}, Weight: {rel['weight']}")

100
================================================================================
Community ID: 0-1, Level: 0
Nodes:
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:422, Name: Cảm cúm, Description: A common respiratory infection characterized by symptoms such as fever, cough, and sore throat.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:318, Name: Hội chứng antiphospholipid, Description: A blood clotting disorder that can cause recurrent miscarriages and placental issues.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:561, Name: Trung tâm Sản phụ khoa, Description: A specialized department within the hospital that focuses on gynecological care, including examinations and health services for women.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:321, Name: Phụ nữ bị sảy thai nhiều lần, Description: A condition referring to women who have experienced multiple miscarriages without identifying a cause.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:319, Name: Bất đồng nhóm máu mẹ con, Description: A blood group incompatibility between the mother and fetus that can lead to complications during pregnancy.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:295, Name: Thai chung buồng ối, Description: A common type of pregnancy where the baby is in the mother's abdomen and the placenta is attached to the uterine wall.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:404, Name: Đặt lịch khám, Description: The process of scheduling an appointment with a specialist at the hospital.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:617, Name: Ngủ nghỉ hợp lý, Description: A balanced sleep schedule that supports overall health and recovery during pregnancy.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:441, Name: Đặt lịch khám, Description: Appointments for medical examinations are scheduled to ensure timely and effective treatment and care for patients.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:454, Name: Trung tâm Hỗ trợ sinh sản, Description: A department within the hospital providing reproductive health support and care.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:564, Name: Nhân viên hỗ trợ, Description: Support staff at the hospital who assist patients with inquiries and administrative tasks.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:619, Name: Hủy chu kỳ, Description: The process of ending a pregnancy, which can be unwanted and requires careful consideration and medical support.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:263, Name: Bệnh viện Đa khoa Tâm Anh, Description: A hospital providing comprehensive medical care, including prenatal care, reproductive health services, and gynecological care, with modern facilities and experienced medical staff.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:301, Name: Khám thai, Description: A prenatal check-up to monitor the health of the mother and fetus.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:423, Name: Lương Thanh Thảo, Description: A substance or ingredient possibly affecting pregnancy, though no research has been conducted on its impact.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:522, Name: chi phí trung bình 1 chu kỳ kích trứng, Description: The average cost of a single cycle of oocyte stimulation, which varies based on treatment plan and additional expenses.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:350, Name: Trung tâm Sản Phụ khoa, Description: A department within the hospital specializing in obstetrics and gynecology, where the patient is referred for further evaluation.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:647, Name: Hồ sơ, Description: A concept representing the documentation and procedures required for sperm donation and reproductive assistance.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:453, Name: Trung tâm Sản phụ khoa, Description: A department within the hospital specializing in gynecological care and reproductive health.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:616, Name: Chế độ tập luyện nhẹ nhàng, Description: A gentle exercise routine that helps maintain physical health and well-being during pregnancy.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:403, Name: Chuyên gia, Description: Experts at the hospital who provide specialized care and guidance to patients.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:443, Name: Hà Nội, Description: The capital city of Vietnam, known for its historical and cultural significance, and home to many hospitals and clinics.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:511, Name: trang thiết bị hiện đại, Description: Modern equipment and technology used in the hospital to support accurate diagnosis and treatment of reproductive health conditions.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:317, Name: Bất thường nhiễm sắc thể, Description: A genetic abnormality that can lead to miscarriages, especially in cases of repeated miscarriages.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:424, Name: Vaccine ngừa Covid-19, Description: A vaccine developed to prevent infection with the SARS-CoV-2 virus, which causes Covid-19.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:489, Name: Trung tâm Sản Phụ khoa, Description: A department within the hospital that specializes in obstetrics and gynecology, providing medical care and examinations for women.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:406, Name: Tổng đài, Description: A phone number provided by the hospital for patients to contact for assistance in scheduling appointments.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:524, Name: 024 3872 3872, Description: A phone number for the hospital in Hanoi.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:589, Name: Dị tật, Description: A congenital abnormality or birth defect, which may be misdiagnosed in some cases, such as umbilical herniation.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:487, Name: Chu kỳ kinh, Description: The menstrual cycle of women in reproductive age (21–35 years old) is considered normal, from the first day of one cycle to the first day of the next. However, the length of the cycle may be affected by neurological factors and health status. If your cycle is within the normal range, there is no need to be concerned. If you are still worried about your condition, you should visit the Obstetrics and Gynecology Center at Tâm Anh Hospital.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:296, Name: Thai chung bánh rau, Description: A common type of pregnancy where the baby is in the mother's abdomen and the placenta is attached to the uterine wall.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:620, Name: Thai kỳ sắp tới, Description: Pregnancy that is approaching, requiring proper preparation and care to ensure a healthy outcome.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:440, Name: Tư vấn, Description: Consultation is a service provided by healthcare professionals to help patients understand their medical conditions, treatment options, and care plans.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:315, Name: Dị tật bẩm sinh, Description: A birth defect that can result from infections during pregnancy.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:614, Name: Thiền định, Description: A practice of mindfulness and relaxation, recommended for stress relief and maintaining a balanced lifestyle.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:615, Name: Thực phẩm đa dạng, Description: A variety of foods such as green vegetables, soy products, meat, and dairy, which are recommended for a healthy diet during pregnancy.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:646, Name: Ngân hàng tinh trùng, Description: A concept representing a bank for storing and preserving sperm samples for future use.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:300, Name: Nguy cơ cao, Description: A high risk for complications during pregnancy, requiring close monitoring and specialized care.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:525, Name: 0287 102 6789, Description: A phone number for the hospital in Ho Chi Minh City.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:618, Name: Phác đồ điều trị, Description: A treatment plan prescribed by doctors, which patients are encouraged to trust and follow for optimal health outcomes.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:651, Name: Trung tâm Hỗ trợ sinh sản IVFTA, Description: A center providing reproductive assistance services, including sperm donation and IVF procedures.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:277, Name: Trung tâm Sản Phụ khoa, Description: A department within the hospital specializing in prenatal care and gynecological services.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:402, Name: Tư vấn, Description: Provided by the hospital to assist patients in making informed decisions about their healthcare.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:444, Name: TP.HCM, Description: The capital city of the province of Gia Lai, known for its natural beauty and cultural heritage, and home to many hospitals and clinics.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:405, Name: Khám sớm, Description: Scheduling an early appointment for a consultation to receive assistance from the hospital.
  - ID: 4:7db85d1f-e5ef-4e9b-8116-a375dae1eab3:297, Name: Thai kì kéo dài 9 tháng 10 ngày, Description: A prolonged pregnancy lasting 9 months and 10 days, which is considered high-risk.
Relationships:
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: chi phí trung bình 1 chu kỳ kích trứng, Description: The healthcare system provides support for the cost of oocyte stimulation, which varies based on treatment plan and additional expenses., Weight: 6.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Khám sớm, Description: The hospital encourages patients to schedule early appointments for consultations to receive assistance., Weight: 5.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Tư vấn, Description: The hospital provides consultation services to assist patients in making informed healthcare decisions., Weight: 7.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Thiền định, Description: Relaxation techniques like meditation are recommended for stress relief and maintaining a balanced lifestyle, as suggested by the hospital's guidance., Weight: 7.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Dị tật bẩm sinh, Description: The hospital is the place where the patient's question was referred, and the doctor is authorized to answer the patient's concerns., Weight: 7.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Dị tật, Description: The hospital is involved in diagnosing and evaluating congenital abnormalities, including umbilical herniation., Weight: 5.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Hồ sơ, Description: The hospital is handling the documentation and procedures required for sperm donation and reproductive assistance., Weight: 7.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Thai kỳ sắp tới, Description: Pregnancy is approaching, and the hospital provides guidance on preparing for and managing this period of life., Weight: 7.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Trung tâm Hỗ trợ sinh sản, Description: The hospital has a reproductive health support department, which is part of its comprehensive services., Weight: 5.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Bất thường nhiễm sắc thể, Description: The hospital is the place where the patient's question was referred, and the doctor is authorized to answer the patient's concerns., Weight: 7.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Nhân viên hỗ trợ, Description: The hospital has support staff who assist patients with inquiries and administrative tasks., Weight: 6.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Thai chung bánh rau, Description: The hospital provides care for a common type of pregnancy with high risk., Weight: 7.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Bất đồng nhóm máu mẹ con, Description: The hospital is the place where the patient's question was referred, and the doctor is authorized to answer the patient's concerns., Weight: 7.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Thai chung buồng ối, Description: The hospital provides care for a common type of pregnancy with high risk., Weight: 7.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Hủy chu kỳ, Description: The process of ending a pregnancy is discussed as a potential option, but it requires careful consideration and medical support, as mentioned in the hospital's guidance., Weight: 6.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Lương Thanh Thảo, Description: The hospital is offering consultation and diagnostic services for potential effects of Lương Thanh Thảo on pregnancy., Weight: 5.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Tư vấn, Description: The hospital offers consultation services to patients undergoing fertility treatments., Weight: 7.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: 0287 102 6789, Description: The hotline provides contact information for the hospital in Ho Chi Minh City., Weight: 5.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Ngủ nghỉ hợp lý, Description: A balanced sleep schedule is recommended to support overall health and recovery during pregnancy, as advised by the hospital., Weight: 7.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Trung tâm Sản phụ khoa, Description: The hospital's gynecological department is a specialized unit within the hospital that provides comprehensive care for women., Weight: 8.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Chế độ tập luyện nhẹ nhàng, Description: A gentle exercise routine is recommended to maintain physical health and well-being during pregnancy, as suggested by the hospital., Weight: 7.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: 024 3872 3872, Description: The healthcare system provides contact information for support and assistance in Hà Nội., Weight: 5.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Đặt lịch khám, Description: The hospital provides appointment scheduling services to patients., Weight: 6.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Tổng đài, Description: The hospital provides phone numbers for patients to contact for assistance in scheduling appointments., Weight: 4.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Vaccine ngừa Covid-19, Description: The hospital is providing information about the vaccine and its effects on pregnancy., Weight: 4.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Cảm cúm, Description: The hospital is providing diagnostic and consultation services for respiratory infections like colds., Weight: 6.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Nguy cơ cao, Description: The hospital provides specialized care for high-risk pregnancies., Weight: 7.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Phác đồ điều trị, Description: The hospital encourages patients to trust and follow the treatment plan prescribed by doctors for optimal health outcomes., Weight: 8.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Khám thai, Description: The hospital offers prenatal check-ups to monitor the health of pregnant women and their fetuses., Weight: 8.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Trung tâm Sản phụ khoa, Description: The hospital has a specialized department for gynecological care, which is part of its comprehensive services., Weight: 5.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Trung tâm Sản Phụ khoa, Description: The hospital includes a department specializing in prenatal care and gynecological services., Weight: 8.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Trung tâm Sản Phụ khoa, Description: The hospital gathers a team of experienced doctors and provides comprehensive medical care and examinations for women., Weight: 8.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Ngân hàng tinh trùng, Description: The hospital is providing sperm donation services, which are facilitated through a concept of a sperm bank., Weight: 7.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Chu kỳ kinh, Description: The hospital provides medical care and examinations for women, including the menstrual cycle., Weight: 9.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Hội chứng antiphospholipid, Description: The hospital is the place where the patient's question was referred, and the doctor is authorized to answer the patient's concerns., Weight: 7.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Đặt lịch khám, Description: The hospital provides appointment services for medical examinations and treatments., Weight: 7.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Chuyên gia, Description: The hospital offers specialized care and guidance from its experts to patients., Weight: 8.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Trung tâm Sản Phụ khoa, Description: The hospital's gynecology department is responsible for evaluating and managing the condition., Weight: 9.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: trang thiết bị hiện đại, Description: The hospital is equipped with modern technology to support accurate diagnosis and treatment of reproductive health conditions., Weight: 7.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Thực phẩm đa dạng, Description: A variety of foods such as green vegetables, soy products, meat, and dairy are recommended for a healthy diet during pregnancy, as advised by the hospital., Weight: 8.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Thai kì kéo dài 9 tháng 10 ngày, Description: The hospital provides care for prolonged pregnancies with high risk., Weight: 6.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Phụ nữ bị sảy thai nhiều lần, Description: The hospital is the place where the patient's question was referred, and the doctor is authorized to answer the patient's concerns., Weight: 7.0
  - Start: Bệnh viện Đa khoa Tâm Anh, Type: RELATED_TO, End: Bệnh viện Đa khoa Tâm Anh, Description: The same entity, with a name variation., Weight: 10.0
  - Start: Hà Nội, Type: RELATED_TO, End: Bệnh viện Đa khoa Tâm Anh, Description: Hà Nội is the location of the hospital, which serves patients in the capital city., Weight: 6.0
  - Start: TP.HCM, Type: RELATED_TO, End: Bệnh viện Đa khoa Tâm Anh, Description: TP.HCM is the location of the hospital, which serves patients in the city of Gia Lai., Weight: 6.0
  - Start: Trung tâm Sản phụ khoa, Type: RELATED_TO, End: Bệnh viện Đa khoa Tâm Anh, Description: The gynecological department is a specialized unit within the hospital that provides comprehensive care for women., Weight: 8.0
  - Start: Trung tâm Hỗ trợ sinh sản IVFTA, Type: RELATED_TO, End: Bệnh viện Đa khoa Tâm Anh, Description: The reproductive assistance center is collaborating with the hospital to provide services for sperm donation and IVF procedures., Weight: 7.0
  - Start: Chu kỳ kinh, Type: RELATED_TO, End: Bệnh viện Đa khoa Tâm Anh, Description: The menstrual cycle is discussed in the context of a hospital that provides medical care and examinations for women., Weight: 7.0
  - Start: Chu kỳ kinh, Type: RELATED_TO, End: Trung tâm Sản Phụ khoa, Description: The menstrual cycle is discussed in the context of a department that specializes in obstetrics and gynecology., Weight: 6.0
================================================================================
Community ID: 0-10, Level: 0
Nodes:

In [11]:
from pydantic import BaseModel, Field


class CommunityReport(BaseModel):

    title: str = Field(description="Short title")

    summary: str = Field(description="Community summary")

    key_entities: list[str] = Field(
        description="Important entities"
    )

    key_relationships: list[str] = Field(
        description="Important relationships"
    )

    findings: list[str] = Field(
        description="Important findings"
    )

In [12]:
from langchain_openai import ChatOpenAI

llm = ChatOpenAI(
    api_key="lm-studio",
    base_url="http://localhost:8000/v1",
    model="qwen-3-1.7b",
    temperature=0,
    extra_body={
        "chat_template_kwargs": {
            "enable_thinking": False
        }
    },
)

structured_llm = llm.with_structured_output(CommunityReport)

In [13]:
from langchain_core.prompts import ChatPromptTemplate

community_prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """
You are an expert knowledge graph analyst.

You analyze graph communities.

Rules:

- Use ONLY the provided information.
- Do NOT hallucinate.
- Explain the main topic.
- Identify important entities.
- Explain important relationships.
- Infer useful findings.

Return a structured report.
"""
        ),

        (
            "human",
            """
Community Level:
{level}

Number of entities:
{num_entities}

Number of relationships:
{num_relationships}

Entities

{entities}

Relationships

{relationships}
"""
        ),
    ]
)

In [14]:
def prepare_string(data):

    entities = []

    for node in data["nodes"]:

        text = f"- {node['name']}"

        if node.get("description"):
            text += f": {node['description']}"

        entities.append(text)

    relationships = []

    for rel in data["rels"]:

        text = (
            f"- {rel['start']} "
            f"--[{rel['type']}]--> "
            f"{rel['end']}"
        )

        if rel.get("strength") is not None:
            text += f" (strength={rel['strength']})"

        if rel.get("description"):
            text += f": {rel['description']}"

        relationships.append(text)

    return {
        "entities": "\n".join(entities),
        "relationships": "\n".join(relationships),
    }

In [15]:
def process_community(community):

    info = prepare_string(community)

    prompt = community_prompt.format_messages(
        level=community["level"],
        num_entities=len(community["nodes"]),
        num_relationships=len(community["rels"]),
        entities=info["entities"],
        relationships=info["relationships"],
    )

    response = structured_llm.invoke(prompt)

    return {
        "community": community["communityId"],
        "title": response.title,
        "summary": response.summary,
        "key_entities": response.key_entities,
        "key_relationships": response.key_relationships,
        "findings": response.findings,
    }

In [16]:
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm

summaries = []

with ThreadPoolExecutor(max_workers=4) as executor:

    futures = [
        executor.submit(process_community, c)
        for c in community_info
    ]

    for future in tqdm(
        as_completed(futures),
        total=len(futures),
        desc="Generating community reports"
    ):

        try:

            summaries.append(future.result())

        except Exception as e:

            print(e)

Generating community reports:   0%|          | 0/100 [00:00<?, ?it/s]

Generating community reports:   6%|▌         | 6/100 [00:23<04:55,  3.15s/it]

Could not parse response content as the length limit was reached - CompletionUsage(completion_tokens=726, prompt_tokens=3370, total_tokens=4096, completion_tokens_details=None, prompt_tokens_details=None)

Generating community reports:  66%|██████▌   | 66/100 [02:53<01:41,  2.98s/it]

Could not parse response content as the length limit was reached - CompletionUsage(completion_tokens=98, prompt_tokens=3998, total_tokens=4096, completion_tokens_details=None, prompt_tokens_details=None)

Generating community reports:  82%|████████▏ | 82/100 [03:59<03:23, 11.32s/it]

Could not parse response content as the length limit was reached - CompletionUsage(completion_tokens=1473, prompt_tokens=2623, total_tokens=4096, completion_tokens_details=None, prompt_tokens_details=None)

Generating community reports:  83%|████████▎ | 83/100 [04:03<02:34,  9.09s/it]

Could not parse response content as the length limit was reached - CompletionUsage(completion_tokens=98, prompt_tokens=3998, total_tokens=4096, completion_tokens_details=None, prompt_tokens_details=None)

Generating community reports: 100%|██████████| 100/100 [04:51<00:00,  2.92s/it]

In [17]:
for summary in summaries[:5]:
    print("=" * 80)
    print(f"Community ID: {summary['community']}")
    print(f"Title: {summary['title']}")
    print(f"Summary: {summary['summary']}")
    print(f"Key Entities: {summary['key_entities']}")
    print(f"Key Relationships: {summary['key_relationships']}")
    print(f"Findings: {summary['findings']}")

================================================================================
Community ID: 0-10
Title: Community Analysis
Summary: The community consists of two entities: 'Thuốc tẩy giun' (Drug used to treat parasitic infections) and 'Phụ nữ có thai' (Pregnant women). There is one relationship: 'RELATED_TO' between the drug and pregnant women, indicating that the drug is used by pregnant women, who are at risk of complications if they take it.
Key Entities: ['Thuốc tẩy giun', 'Phụ nữ có thai']
Key Relationships: ['Thuốc tẩy giun --[RELATED_TO]--> Phụ nữ có thai']
Findings: ["The drug 'Thuốc tẩy giun' is used by pregnant women, who are at risk of complications if they take it.", 'This relationship highlights a potential risk for pregnant women when using the drug, suggesting a need for caution or alternative treatment options.']
================================================================================
Community ID: 0-102
Title: Community Analysis of Reproductive Medicine
Summary: This community focuses on reproductive medicine, particularly on the role of AMH, IVF, and ovarian reserve in fertility treatments.
Key Entities: ['AMH', 'Fertility Treatment', 'Ovarian Reserve', 'IVF']
Key Relationships: ['AMH --[RELATED_TO]--> IVF', 'IVF --[RELATED_TO]--> Ovarian Reserve', 'Fertility Treatment --[RELATED_TO]--> IVF']
Findings: ['AMH is a biomarker used to assess ovarian reserve and is commonly used in conjunction with other factors to predict IVF success rates.', 'IVF is a reproductive technology used to assist in fertility treatments, particularly when ovarian reserve is low.', 'Fertility treatments include IVF as a key component, and IVF is used to assess ovarian reserve, which is crucial for determining fertility outcomes.']
================================================================================
Community ID: 0-113
Title: Community Analysis of Medical Conditions
Summary: This community consists of six entities related to a medical condition involving the Napot cyst, mucus secretion, and related treatments. The community includes procedures, conditions, body parts, and potential complications.
Key Entities: ['Kiểm tra lại (Follow-up Procedure)', 'Tình trạng tiết dịch hồng (Pink Mucus Condition)', 'Napot (Navel Cyst)', 'Điều trị (Treatment Method)', 'Biến chứng (Complication)', 'Tuyến nước bọt (Mucus Secreting Organ)']
Key Relationships: ['Kiểm tra lại --[RELATED_TO]--> Tình trạng tiết dịch hồng: The follow-up procedure is used to check for complications or abnormal symptoms after initial treatment.', 'Tình trạng tiết dịch hồng --[RELATED_TO]--> Napot: The condition is related to the Napot cyst, which may be treated and monitored.', 'Tuyến nước bọt --[RELATED_TO]--> Tình trạng tiết dịch hồng: The mucus secreted by the tuyến nước bọt may be affected by the condition, which is monitored for symptoms.', 'Điều trị --[RELATED_TO]--> Tình trạng tiết dịch hồng: The treatment is used to manage the condition, which may involve monitoring and follow-up care.', 'Biến chứng --[RELATED_TO]--> Tình trạng tiết dịch hồng: The condition may lead to complications, which require medical attention if symptoms appear after the initial period.']
Findings: ['The community includes a procedure (Kiểm tra lại) and a condition (Tình trạng tiết dịch hồng) that are closely related to the Napot cyst.', "The mucus secreted by the tuyến nước bọt is monitored for symptoms, which may indicate the condition's impact on the body.", 'Treatment (Điều trị) involves monitoring and follow-up care, which is linked to the condition and its complications.', 'The condition may lead to complications (Biến chứng), which require medical attention if symptoms appear after the initial period.']
================================================================================
Community ID: 0-127
Title: Reproductive Health Assessment
Summary: The provided knowledge graph represents a reproductive health assessment process involving multiple tests and relationships between entities. The main focus is on evaluating fertility and reproductive health through various diagnostic tests, including semen analysis, cervical screening, breast screening, hormone testing, and imaging studies.
Key Entities: ['XN tinh dịch đồ Miễn dịch', 'XN sàng lọc K cổ tử cung', 'Vợ', 'XN sàng lọc K vú', 'Chụp phim tử cung – vòi trứng', 'Xét nghiệm nội tiết sinh sản', 'Sach kinh 3 – 5 ngày', 'Siêu âm']
Key Relationships: ['Vợ is related to XN tinh dịch đồ Miễn dịch', 'Vợ is related to Sach kinh 3 – 5 ngày', 'Vợ is related to XN sàng lọc K cổ tử cung', 'Vợ is related to Xét nghiệm nội tiết sinh sản', 'Vợ is related to Chụp phim tử cung – vòi trứng', 'Vợ is related to Siêu âm', 'Vợ is related to XN sàng lọc K vú']
Findings: ['The reproductive health assessment includes multiple tests such as semen analysis, cervical screening, breast screening, hormone testing, and imaging studies.', 'The spouse is involved in the reproductive health assessment and is linked to several diagnostic tests.', 'The tests are related to fertility, reproductive health, and hormonal status.', 'The tests are performed in a gynecological context, with some tests being conditional (e.g., breast screening if the patient is over 35).']
================================================================================
Community ID: 0-133
Title: Community Analysis
Summary: This community consists of two entities: 'Tiêm vaccine' (vaccination) and 'Mũi thứ 2' (second dose of a vaccine). There is one relationship: 'RELATED_TO' between them, indicating that the second dose is administered after the first dose to enhance immunity.
Key Entities: ['Tiêm vaccine', 'Mũi thứ 2']
Key Relationships: ['Tiêm vaccine --[RELATED_TO]--> Mũi thứ 2']
Findings: ["The relationship between 'Tiêm vaccine' and 'Mũi thứ 2' indicates that the second dose (Mũi thứ 2) is a subsequent administration of the vaccine to strengthen the immune response.", 'This community is simple and contains only two entities with a single, clear relationship.']

In [ ]:
def build_community_text(row):

    title = row["title"] or ""
    summary = row["summary"] or ""

    return f"""
        Title:
        {title}

        Summary:
        {summary}
        """.strip()

In [ ]:
texts = [
    build_community_text(r)
    for r in summaries
]
model = SentenceTransformer(
    "bkai-foundation-models/vietnamese-bi-encoder"
)

embeddings = model.encode(
    texts,
    batch_size=128,
    normalize_embeddings=True,
    show_progress_bar=True
).tolist()

for report, emb in zip(summaries, embeddings):
    report["embedding"] = emb

In [ ]:
save_query = """
UNWIND $rows AS row

MATCH (c:Community {id: row.community})

SET
    c.title = row.title,
    c.summary = row.summary,
    c.key_entities = row.key_entities,
    c.key_relationships = row.key_relationships,
    c.findings = row.findings,
    c.embedding = row.embedding
"""

gds.run_cypher(
    save_query,
    params={
        "rows": summaries
    }
)

Empty DataFrame
Columns: []
Index: []